/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PoliticaDeDatosRouteImport } from './routes/politica-de-datos'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PreregistroIndexRouteImport } from './routes/preregistro.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as PreregistroExitoRouteImport } from './routes/preregistro.exito'
import { Route as AdminTarifasRouteImport } from './routes/admin.tarifas'
import { Route as AdminReportesRouteImport } from './routes/admin.reportes'
import { Route as AdminRegistroRouteImport } from './routes/admin.registro'
import { Route as AdminPagosRouteImport } from './routes/admin.pagos'
import { Route as AdminConfiguracionRouteImport } from './routes/admin.configuracion'
import { Route as AdminCheckInRouteImport } from './routes/admin.check-in'
import { Route as AdminVisitantesIndexRouteImport } from './routes/admin.visitantes.index'
import { Route as AdminVisitantesVisitIdRouteImport } from './routes/admin.visitantes.$visitId'

const PoliticaDeDatosRoute = PoliticaDeDatosRouteImport.update({
  id: '/politica-de-datos',
  path: '/politica-de-datos',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PreregistroIndexRoute = PreregistroIndexRouteImport.update({
  id: '/preregistro/',
  path: '/preregistro/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const PreregistroExitoRoute = PreregistroExitoRouteImport.update({
  id: '/preregistro/exito',
  path: '/preregistro/exito',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTarifasRoute = AdminTarifasRouteImport.update({
  id: '/tarifas',
  path: '/tarifas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportesRoute = AdminReportesRouteImport.update({
  id: '/reportes',
  path: '/reportes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRegistroRoute = AdminRegistroRouteImport.update({
  id: '/registro',
  path: '/registro',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPagosRoute = AdminPagosRouteImport.update({
  id: '/pagos',
  path: '/pagos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfiguracionRoute = AdminConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCheckInRoute = AdminCheckInRouteImport.update({
  id: '/check-in',
  path: '/check-in',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVisitantesIndexRoute = AdminVisitantesIndexRouteImport.update({
  id: '/visitantes/',
  path: '/visitantes/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVisitantesVisitIdRoute = AdminVisitantesVisitIdRouteImport.update({
  id: '/visitantes/$visitId',
  path: '/visitantes/$visitId',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/politica-de-datos': typeof PoliticaDeDatosRoute
  '/admin/check-in': typeof AdminCheckInRoute
  '/admin/configuracion': typeof AdminConfiguracionRoute
  '/admin/pagos': typeof AdminPagosRoute
  '/admin/registro': typeof AdminRegistroRoute
  '/admin/reportes': typeof AdminReportesRoute
  '/admin/tarifas': typeof AdminTarifasRoute
  '/preregistro/exito': typeof PreregistroExitoRoute
  '/admin/': typeof AdminIndexRoute
  '/preregistro/': typeof PreregistroIndexRoute
  '/admin/visitantes/$visitId': typeof AdminVisitantesVisitIdRoute
  '/admin/visitantes/': typeof AdminVisitantesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/politica-de-datos': typeof PoliticaDeDatosRoute
  '/admin/check-in': typeof AdminCheckInRoute
  '/admin/configuracion': typeof AdminConfiguracionRoute
  '/admin/pagos': typeof AdminPagosRoute
  '/admin/registro': typeof AdminRegistroRoute
  '/admin/reportes': typeof AdminReportesRoute
  '/admin/tarifas': typeof AdminTarifasRoute
  '/preregistro/exito': typeof PreregistroExitoRoute
  '/admin': typeof AdminIndexRoute
  '/preregistro': typeof PreregistroIndexRoute
  '/admin/visitantes/$visitId': typeof AdminVisitantesVisitIdRoute
  '/admin/visitantes': typeof AdminVisitantesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/politica-de-datos': typeof PoliticaDeDatosRoute
  '/admin/check-in': typeof AdminCheckInRoute
  '/admin/configuracion': typeof AdminConfiguracionRoute
  '/admin/pagos': typeof AdminPagosRoute
  '/admin/registro': typeof AdminRegistroRoute
  '/admin/reportes': typeof AdminReportesRoute
  '/admin/tarifas': typeof AdminTarifasRoute
  '/preregistro/exito': typeof PreregistroExitoRoute
  '/admin/': typeof AdminIndexRoute
  '/preregistro/': typeof PreregistroIndexRoute
  '/admin/visitantes/$visitId': typeof AdminVisitantesVisitIdRoute
  '/admin/visitantes/': typeof AdminVisitantesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/politica-de-datos'
    | '/admin/check-in'
    | '/admin/configuracion'
    | '/admin/pagos'
    | '/admin/registro'
    | '/admin/reportes'
    | '/admin/tarifas'
    | '/preregistro/exito'
    | '/admin/'
    | '/preregistro/'
    | '/admin/visitantes/$visitId'
    | '/admin/visitantes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/politica-de-datos'
    | '/admin/check-in'
    | '/admin/configuracion'
    | '/admin/pagos'
    | '/admin/registro'
    | '/admin/reportes'
    | '/admin/tarifas'
    | '/preregistro/exito'
    | '/admin'
    | '/preregistro'
    | '/admin/visitantes/$visitId'
    | '/admin/visitantes'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/politica-de-datos'
    | '/admin/check-in'
    | '/admin/configuracion'
    | '/admin/pagos'
    | '/admin/registro'
    | '/admin/reportes'
    | '/admin/tarifas'
    | '/preregistro/exito'
    | '/admin/'
    | '/preregistro/'
    | '/admin/visitantes/$visitId'
    | '/admin/visitantes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  PoliticaDeDatosRoute: typeof PoliticaDeDatosRoute
  PreregistroExitoRoute: typeof PreregistroExitoRoute
  PreregistroIndexRoute: typeof PreregistroIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/politica-de-datos': {
      id: '/politica-de-datos'
      path: '/politica-de-datos'
      fullPath: '/politica-de-datos'
      preLoaderRoute: typeof PoliticaDeDatosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preregistro/': {
      id: '/preregistro/'
      path: '/preregistro'
      fullPath: '/preregistro/'
      preLoaderRoute: typeof PreregistroIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/preregistro/exito': {
      id: '/preregistro/exito'
      path: '/preregistro/exito'
      fullPath: '/preregistro/exito'
      preLoaderRoute: typeof PreregistroExitoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tarifas': {
      id: '/admin/tarifas'
      path: '/tarifas'
      fullPath: '/admin/tarifas'
      preLoaderRoute: typeof AdminTarifasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reportes': {
      id: '/admin/reportes'
      path: '/reportes'
      fullPath: '/admin/reportes'
      preLoaderRoute: typeof AdminReportesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/registro': {
      id: '/admin/registro'
      path: '/registro'
      fullPath: '/admin/registro'
      preLoaderRoute: typeof AdminRegistroRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pagos': {
      id: '/admin/pagos'
      path: '/pagos'
      fullPath: '/admin/pagos'
      preLoaderRoute: typeof AdminPagosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/configuracion': {
      id: '/admin/configuracion'
      path: '/configuracion'
      fullPath: '/admin/configuracion'
      preLoaderRoute: typeof AdminConfiguracionRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/check-in': {
      id: '/admin/check-in'
      path: '/check-in'
      fullPath: '/admin/check-in'
      preLoaderRoute: typeof AdminCheckInRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/visitantes/': {
      id: '/admin/visitantes/'
      path: '/visitantes'
      fullPath: '/admin/visitantes/'
      preLoaderRoute: typeof AdminVisitantesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/visitantes/$visitId': {
      id: '/admin/visitantes/$visitId'
      path: '/visitantes/$visitId'
      fullPath: '/admin/visitantes/$visitId'
      preLoaderRoute: typeof AdminVisitantesVisitIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminCheckInRoute: typeof AdminCheckInRoute
  AdminConfiguracionRoute: typeof AdminConfiguracionRoute
  AdminPagosRoute: typeof AdminPagosRoute
  AdminRegistroRoute: typeof AdminRegistroRoute
  AdminReportesRoute: typeof AdminReportesRoute
  AdminTarifasRoute: typeof AdminTarifasRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminVisitantesVisitIdRoute: typeof AdminVisitantesVisitIdRoute
  AdminVisitantesIndexRoute: typeof AdminVisitantesIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCheckInRoute: AdminCheckInRoute,
  AdminConfiguracionRoute: AdminConfiguracionRoute,
  AdminPagosRoute: AdminPagosRoute,
  AdminRegistroRoute: AdminRegistroRoute,
  AdminReportesRoute: AdminReportesRoute,
  AdminTarifasRoute: AdminTarifasRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminVisitantesVisitIdRoute: AdminVisitantesVisitIdRoute,
  AdminVisitantesIndexRoute: AdminVisitantesIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  PoliticaDeDatosRoute: PoliticaDeDatosRoute,
  PreregistroExitoRoute: PreregistroExitoRoute,
  PreregistroIndexRoute: PreregistroIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
